
name: Rehid-Build-CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run -e ENABLE_COMPATIBILITY_REPORTING -v $GITHUB_WORKSPACE:/build_dir devkitpro/devkitarm /bin/bash -ex /build_dir/.github/workflows/build.sh
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 0004013000001D02
        path: ./0004013000001D02/